### PR TITLE
Add support for committing with no-verify

### PR DESCRIPTION
**Pull request by becky-sequence**

### CODE REVIEW

**Comment by peter-evans** [comment]
Hi @becky-sequence 

Please check this past issue: https://github.com/peter-evans/create-pull-request/issues/935#issuecomment-1358830735

Does [this](https://github.com/peter-evans/create-pull-request/issues/935#issuecomment-1404312978) solve your problem?

If not, please can you explain in detail what your use case is, and why git hooks are enabled when you checkout.

**Comment by becky-sequence** [comment]
> Hi @becky-sequence
> 
> Please check this past issue: [#935 (comment)](https://github.com/peter-evans/create-pull-request/issues/935#issuecomment-1358830735)
> 
> Does [this](https://github.com/peter-evans/create-pull-request/issues/935#issuecomment-1404312978) solve your problem?
> 
> If not, please can you explain in detail what your use case is, and why git hooks are enabled when you checkout.

Hi @peter-evans 

I've tried a few different things here and am still having issues. What I think I actually want to do is disable hooks for both the commit and the push (this PR just addresses the commit step). We have a pre-commit hook that does some linting and then a pre-push hook that runs all our tests. I'd rather turn off these hooks for these automated PRs because if the tests are going to fail I'd prefer to have an open PR with failing tests to give visibility of this. Even if I manually perform a commit and push with the `--no-verify` option, it seems the action still does another push and then things fall over.

I don't think adding `--no-verify` is a particular edge case so think it would be a useful addition to this action.

**Comment by peter-evans** [comment]
Hi @becky-sequence 

> I'd rather turn off these hooks for these automated PRs

Please can you show me your workflow. Feel free to redact anything that might be sensitive. I would like to understand how the hooks are active, because my understanding is that they need to be installed after checkout. If you happen to be using Husky, there is a solution shared [here](https://github.com/peter-evans/create-pull-request/issues/935#issuecomment-1404312978).

I want to understand more about your use case, but my current order of preference to solve this is:
1. Don't install the hooks after checkout in the first place
2. If the hooks are automatically enabled by some framework (like Husky), use an option to disable them if it exists.
3. Just delete the hooks in the workflow after checkout.
    ```yml
   - run: rm -rf .git/hooks
   ```

As I explained in [this comment](https://github.com/peter-evans/create-pull-request/issues/935#issuecomment-1358830735), I'm really trying hard to keep the interface for this action to a minimum to stop it becoming bloated and complicated.

**Comment by peter-evans** [comment]
For anyone finding this, there is now a section in the "common issues" doc about it here: https://github.com/peter-evans/create-pull-request/blob/main/docs/common-issues.md#add-a-no-verify-option-to-bypass-git-hooks

**Pull request closed without merging**
