### PR TITLE
Add support for signed commits

### PR DESCRIPTION
**Pull request by rustycl0ck**
Add support for automatically signing the commits as `github-actions` bot. This is useful in cases where repo/org owners have enforced a signed-commit policy. If a custom github-token is provided for another Github App, then the commit will be signed as that app.

This PR is related to or addresses the following issues:
- #1936 
- #1607 
- #1241 
- #1162
- #1055 
- #708 

I am a newbie with Typescript, so I have not separated out the logic to a different file or broken it into smaller functions/utilities. I might be able to spend a little bit more time on it to implement suggestions, but if it requires major refactoring, then please feel free to refactor and push the commits directly (or can also merge this PR and then refactor separately in a new PR).

### CODE REVIEW

**Comment by peter-evans** [comment]
Thank you for contributing this feature! Your timing is impeccable. I was just talking with a colleague today about needing this feature!

If I understand correctly, this only works for [app-generated tokens](https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#authenticating-with-github-app-generated-tokens), correct? I wonder what happens if you try to sign with a PAT. I guess the default `GITHUB_TOKEN` counts as an app token of the `github-actions` bot. Anyway, I'll test it and confirm.

**Comment by peter-evans** [comment]
I tried to make changes directly to your branch, but I don't have permission it seems. I'll merge to a feature branch before merging to `main`.

**Comment by rustycl0ck** [comment]
Thank you for picking up this PR so quickly and for improving. Looking forward to seeing this feature in a new release soon!

**Comment by peter-evans** [comment]
There's quite a bit of work to do before I can release this, but your contribution is a great start. Thank you!

Working on it here:
- https://github.com/peter-evans/create-pull-request/pull/3057

**Comment by rustycl0ck** [comment]
Ah I see... Yes, that looks like a lot of work really! Just passing all the test cases itself would have been quite challenging for me. Thank you very much for continuing to maintain this very useful Github Action and for continuing to add features.

**Pull request merged**
