### PR TITLE
fix: reset branches to handle squash merge

### PR DESCRIPTION
**Pull request by peter-evans**
ref: https://github.com/async-aws/aws/pull/767

### CODE REVIEW

**Review by jderusse — APPROVED** [review]
thank you !

**Comment by peter-evans** [comment]
@jderusse I've simplified the solution to checking if the `tempBranch` (the recreated base + changes) is not ahead of the base. This means if the branch is reset, there won't be any diff with the base. The changes cause the branch to be reset and then be deleted because there is no diff. The side effect of this change is that not only squash merged branches, but any branches that are undeleted after merging will be reset, and (currently) the branch will then be deleted because there is no diff. I think this is a good side effect and a nice feature. Basically, if you forgot to delete a branch after merging, the action will delete it next time it runs.

However, there have been cases where users have not read the documentation before using the action and assume they can put an existing branch (e.g. `develop`) in the `branch` input. This can lead to the action deleting it if it has no diff with the base. To try and protect users from accidentally deleting branches I'm planning to add an additional input and default to not deleting. See https://github.com/peter-evans/create-pull-request/pull/547
Not deleting merged branches shouldn't be a problem. It will just mean that the action "maintains" the branch by resetting it until it finds a diff again.

**Comment by jderusse** [comment]
sounds good to me. Thanks

**Pull request merged**
