### PR TITLE
feat: add input to enable gpg commit signing

### PR DESCRIPTION
**Pull request by peter-evans**
Fixes: https://github.com/peter-evans/create-pull-request/issues/708

### CODE REVIEW

**Review by AraHaan — APPROVED** [review]

**Comment by AraHaan** [comment]
@davidboweninrupt this action actually does the commiting and pushing of the data to a branch for you and as such would have to tell git to gpg sign the commit.

**Comment by davidboweninrupt** [comment]
@AraHaan I thought so too, but I had this working before the new feature came online just by using `ghaction-import-gpg`.

I think it's because I'm setting `git-commit-gpgsign: true` during the GPG import which sets `commit.gpgsign` to true (which is what I was verifying this afternoon).

Once that flag is set [the docs say](https://docs.github.com/en/github/authenticating-to-github/signing-commits):

>To sign all commits by default in any local repository on your computer, run git config --global commit.gpgsign true.

which means you don't need to pass the switch to each invocation (which is what I believe the new feature is doing).

Of course there might be something I'missing.

**Comment by peter-evans** [comment]
@davidboweninrupt I think you're right. I overlooked the fact it was setting git's global config. I'm going to test it myself and make a fix to remove the `gpg-sign` input because it appears to be unnecessary.

> I think I'd envisaged you doing something like ghaction-import-gpg does, but if you'd prefer to use it in the pipeline to specify the details of the GPG setup then I don't believe you needed this new capability in create-pull-request. I'm fine with including the other action in my pipeline if that's the preferred approach.

Yes, this is my preferred approach. `ghaction-import-gpg` appears to be well maintained and does the job well so I don't think there is any reason to try and duplicate that logic in this action at the moment.

**Comment by peter-evans** [comment]
Removed the `gpg-sign` input in https://github.com/peter-evans/create-pull-request/pull/804

**Pull request merged**
